# Generated by Django 2.0 on 2017-12-08 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learn', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('user_sex', models.IntegerField(default=1)),
                ('user_password', models.CharField(max_length=200)),
                ('user_email', models.CharField(max_length=200)),
                ('user_phone', models.CharField(max_length=50)),
                ('user_register_time', models.DateTimeField(verbose_name='Date user register')),
                ('user_login_time', models.DateTimeField(verbose_name='Date user login')),
            ],
        ),
    ]
